#   server:
#   port: ��Ϊ��������� product-data-service, ���Զ˿ں����û��Զ����ã��Ƽ� 8001,8002,8003

spring:
  application:
    name: product-data-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
